export const data = [
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Fine particulate matter formation",
    Unit: "kg PM2.5 eq",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0032",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Fossil resource scarcity",
    Unit: "kg oil eq",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0037",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Freshwater ecotoxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0016",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Freshwater eutrophication",
    Unit: "kg P eq",
    Recipe: "2,00",
    "Impact Value": "0,0000492",
    "Cost Value": "CHF 0,0000",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Global warming",
    Unit: "kg CO2 eq",
    Recipe: "2,00",
    "Impact Value": "0,000492",
    "Cost Value": "CHF 0,0163",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Human carcinogenic toxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0009",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Human non-carcinogenic toxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0334",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Ionizing radiation",
    Unit: "kBq Co-60 eq",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0004",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Land use",
    Unit: "m2a crop eq",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0160",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Marine ecotoxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0012",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Marine eutrophication",
    Unit: "kg N eq",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0000",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Mineral resource scarcity",
    Unit: "kg Cu eq",
    Recipe: "2,00",
    "Impact Value": "0,0000492",
    "Cost Value": "CHF 0,0001",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Ozone formation, Human health",
    Unit: "kg NOx eq",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0001",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Ozone formation, Terrestrial ecosystems",
    Unit: "kg NOx eq",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0001",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Stratospheric ozone depletion",
    Unit: "kg CFC11 eq",
    Recipe: "2,00",
    "Impact Value": "0,0000492",
    "Cost Value": "CHF 0,0000",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Terrestrial acidification",
    Unit: "kg SO2 eq",
    Recipe: "2,00",
    "Impact Value": "0,000369",
    "Cost Value": "CHF 0,0002",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Terrestrial ecotoxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0649",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Water consumption",
    Unit: "m3",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0023",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Fine particulate matter formation",
    Unit: "kg PM2.5 eq",
    Recipe: "2,00",
    "Impact Value": "0,00246",
    "Cost Value": "CHF 0,0000",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Fossil resource scarcity",
    Unit: "kg oil eq",
    Recipe: "2,00",
    "Impact Value": "0,000246",
    "Cost Value": "CHF 0,0034",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Freshwater ecotoxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0015",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Freshwater eutrophication",
    Unit: "kg P eq",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0000",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Global warming",
    Unit: "kg CO2 eq",
    Recipe: "2,00",
    "Impact Value": "0,00123",
    "Cost Value": "CHF 0,0180",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Human carcinogenic toxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,0000738",
    "Cost Value": "CHF 0,0008",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Human non-carcinogenic toxicity",
    Unit: "kg 1,4-DCB",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0310",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Health",
    Indicators: "Ionizing radiation",
    Unit: "kBq Co-60 eq",
    Recipe: "2,00",
    "Impact Value": "0,000492",
    "Cost Value": "CHF 0,0005",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
  {
    "Retail-Name": "Ristretto",
    "Product-ID": "cof-braz-ara-conv",
    "Product-Name": "Coffee, Brazil, Arabica, none",
    Stage: "Cultivation",
    "Impact-Category": "Environment",
    Indicators: "Land use",
    Unit: "m2a crop eq",
    Recipe: "2,00",
    "Impact Value": "0,000123",
    "Cost Value": "CHF 0,0185",
    "Impact-Definition": "Impact short definition",
    "Coffee-Details": "Name definition",
    Reference: "International Coffee Council, MRL",
  },
];
